"""Configuration loading for Project Akiha."""

from project_akiha.config.settings import (
    AI_PROVIDERS,
    GMAIL_REDIRECT_URI,
    HOSTED_AI_PROVIDERS,
    SPOTIFY_REDIRECT_URI,
    AIConfig,
    AppConfig,
    BehaviorConfig,
    DiscordIntegrationConfig,
    ExternalIntegrationsConfig,
    GmailIntegrationConfig,
    MemoryConfig,
    PersonalityConfig,
    PetWindowConfig,
    PrivacyConfig,
    SpotifyConfig,
    VoiceConfig,
    ai_text_processing_is_remote,
    load_config,
)

__all__ = [
    "AI_PROVIDERS",
    "AIConfig",
    "AppConfig",
    "BehaviorConfig",
    "DiscordIntegrationConfig",
    "ExternalIntegrationsConfig",
    "GMAIL_REDIRECT_URI",
    "GmailIntegrationConfig",
    "HOSTED_AI_PROVIDERS",
    "MemoryConfig",
    "PetWindowConfig",
    "PersonalityConfig",
    "PrivacyConfig",
    "SPOTIFY_REDIRECT_URI",
    "SpotifyConfig",
    "VoiceConfig",
    "ai_text_processing_is_remote",
    "load_config",
]
