"""Typed contracts for Akiha's trusted local shop and wardrobe."""

from project_akiha.core.shop.catalog import (
    SHOP_CATALOG_SCHEMA_VERSION,
    CatalogDecodeError,
    CatalogError,
    CatalogLoadFailure,
    CatalogLoadResult,
    CatalogOwnershipFilter,
    CatalogQuery,
    CatalogReadError,
    CatalogSort,
    CatalogValidationError,
    ShopCatalog,
    browse_catalog,
    load_catalog,
    load_catalog_or_empty,
    parse_catalog_toml,
)
from project_akiha.core.shop.models import (
    CANONICAL_COSMETIC_CANVAS_SIZE,
    AcquisitionSource,
    CatalogAvailability,
    CatalogItem,
    CosmeticLayer,
    EquipmentLoadout,
    EquipmentSlot,
    EquippedItem,
    FacingDirection,
    InventoryItem,
    PurchaseDecision,
    PurchaseOutcome,
    PurchaseTransaction,
    ShopItemCategory,
)

__all__ = [
    "CANONICAL_COSMETIC_CANVAS_SIZE",
    "SHOP_CATALOG_SCHEMA_VERSION",
    "AcquisitionSource",
    "CatalogAvailability",
    "CatalogDecodeError",
    "CatalogError",
    "CatalogItem",
    "CatalogLoadFailure",
    "CatalogLoadResult",
    "CatalogOwnershipFilter",
    "CatalogQuery",
    "CatalogReadError",
    "CatalogSort",
    "CatalogValidationError",
    "CosmeticLayer",
    "EquipmentLoadout",
    "EquipmentSlot",
    "EquippedItem",
    "FacingDirection",
    "InventoryItem",
    "PurchaseDecision",
    "PurchaseOutcome",
    "PurchaseTransaction",
    "ShopCatalog",
    "ShopItemCategory",
    "browse_catalog",
    "load_catalog",
    "load_catalog_or_empty",
    "parse_catalog_toml",
]
