"""Typed contracts for Akiha's trusted local appearance shop."""

from project_akiha.core.shop.catalog import (
    SHOP_CATALOG_SCHEMA_VERSION,
    CatalogDecodeError,
    CatalogError,
    CatalogLoadFailure,
    CatalogLoadResult,
    CatalogOwnershipFilter,
    CatalogQuery,
    CatalogReadError,
    CatalogSort,
    CatalogValidationError,
    ShopCatalog,
    browse_catalog,
    load_catalog,
    load_catalog_or_empty,
    parse_catalog_toml,
)
from project_akiha.core.shop.models import (
    AcquisitionSource,
    CatalogAvailability,
    CatalogItem,
    InventoryItem,
    PurchaseDecision,
    PurchaseOutcome,
    PurchaseTransaction,
    ShopItemCategory,
)
from project_akiha.core.shop.operations import (
    ShopBrowseResult,
    ShopInspectDecision,
    ShopInspectResult,
    ShopInventoryItemView,
    ShopItemView,
    ShopPurchaseResult,
)
from project_akiha.core.shop.repository import (
    ShopIdempotencyConflictError,
    ShopRepository,
    ShopStateUnavailableError,
)

__all__ = [
    "SHOP_CATALOG_SCHEMA_VERSION",
    "AcquisitionSource",
    "CatalogAvailability",
    "CatalogDecodeError",
    "CatalogError",
    "CatalogItem",
    "CatalogLoadFailure",
    "CatalogLoadResult",
    "CatalogOwnershipFilter",
    "CatalogQuery",
    "CatalogReadError",
    "CatalogSort",
    "CatalogValidationError",
    "InventoryItem",
    "PurchaseDecision",
    "PurchaseOutcome",
    "PurchaseTransaction",
    "ShopCatalog",
    "ShopBrowseResult",
    "ShopIdempotencyConflictError",
    "ShopInspectDecision",
    "ShopInspectResult",
    "ShopInventoryItemView",
    "ShopItemCategory",
    "ShopItemView",
    "ShopPurchaseResult",
    "ShopRepository",
    "ShopStateUnavailableError",
    "browse_catalog",
    "load_catalog",
    "load_catalog_or_empty",
    "parse_catalog_toml",
]
