[animations.idle]
frames = [
    "akiha/idle/palette-v3/000.png",
    "akiha/idle/palette-v3/001.png",
    "akiha/idle/palette-v3/002.png",
    "akiha/idle/palette-v3/003.png",
    "akiha/idle/palette-v3/004.png",
    "akiha/idle/palette-v3/005.png",
    "akiha/idle/palette-v3/006.png",
    "akiha/idle/palette-v3/007.png",
    "akiha/idle/palette-v3/008.png",
    "akiha/idle/palette-v3/009.png",
    "akiha/idle/palette-v3/010.png",
    "akiha/idle/palette-v3/011.png",
    "akiha/idle/palette-v3/012.png",
    "akiha/idle/palette-v3/013.png",
    "akiha/idle/palette-v3/014.png",
    "akiha/idle/palette-v3/015.png",
    "akiha/idle/palette-v3/016.png",
    "akiha/idle/palette-v3/017.png",
    "akiha/idle/palette-v3/018.png",
    "akiha/idle/palette-v3/019.png",
    "akiha/idle/palette-v3/020.png",
    "akiha/idle/palette-v3/021.png",
    "akiha/idle/palette-v3/022.png",
    "akiha/idle/palette-v3/023.png",
    "akiha/idle/palette-v3/024.png",
    "akiha/idle/palette-v3/025.png",
    "akiha/idle/palette-v3/026.png",
    "akiha/idle/palette-v3/027.png",
    "akiha/idle/palette-v3/028.png",
    "akiha/idle/palette-v3/029.png",
    "akiha/idle/palette-v3/030.png",
    "akiha/idle/palette-v3/031.png",
]
ticks_per_frame = 1
x_offset = 0
y_offset = 0
scale_percent = 100

[animations.dragging]
frames = ["akiha/standing/000.png"]
ticks_per_frame = 24
x_offset = 0
y_offset = 0
scale_percent = 100

[animations.walking]
filmstrip = "akiha/walking/Akiha-Walking.png"
frame_width = 100
frame_height = 100
frame_count = 8
ticks_per_frame = 3
x_offset = 0
y_offset = 0
scale_percent = 100

[animations.sleeping]
frames = ["akiha/standing/000.png"]
ticks_per_frame = 24
x_offset = 0
y_offset = 0
scale_percent = 100
